#187 first version of user documentation
dynawo/dynawo-algorithms pull request #189
Opened 2022-03-08 08:58 UTC by rosiereflo

closes #187

2022-03-14 09:10 UTC, gautierbureau commented
.pdf .log .aux should be removed from the PR

2022-03-14 09:10 UTC, gautierbureau commented
You should add a build-doc and doc commands in envDynawoAlgorithms.sh

2022-03-14 10:13 UTC, rosiereflo commented
done for both remarks.

2022-05-09 14:21 UTC, adriguir requested changes

2022-05-09 14:21 UTC, adriguir commented on documentation/configuringDynawoAlgorithms/DynawoAlgorithmsInputFiles.tex
> +and provide as outputs a file named \textit{results.xml} containing the status of each simulated event,
provides

2022-05-09 14:21 UTC, adriguir commented on documentation/configuringDynawoAlgorithms/DynawoAlgorithmsInputFiles.tex
> +and provide as outputs a file named \textit{results.xml} containing the status of all simulations that were run,
provides

2022-05-09 14:21 UTC, adriguir commented on documentation/configuringDynawoAlgorithms/DynawoAlgorithmsInputFiles.tex
> +in addition to the timelines and constraint files.\\
logs too

2022-05-09 14:21 UTC, adriguir commented on documentation/configuringDynawoAlgorithms/DynawoAlgorithmsInputFiles.tex
> +and provide as outputs a zipped file named \textit{outputs.zip} containing the status of all simulations that were run,
provides

2022-05-09 14:21 UTC, adriguir commented on documentation/configuringDynawoAlgorithms/DynawoAlgorithmsInputFiles.tex
> +in addition to the timelines and constraint files.\\
logs too

2022-05-09 14:21 UTC, adriguir commented on documentation/configuringDynawoAlgorithms/DynawoAlgorithmsInputFiles.tex
> +results file with one result per load increase and one result per scenario for each variation that were simulated.
logs again for SA and MC?

2022-05-09 14:21 UTC, adriguir commented on documentation/introduction/introduction.tex
> +  \item \textbf{Systematic analysis}: simulations of a same base power system subject to different N-k events to assess the global stability;
I would just stick to different events (not necessarily N-k)

2022-05-12 06:52 UTC, adriguir approved these changes

2022-05-12 06:53 UTC, merged