#228 update readme following v1.3.0 release
dynawo/dynawo-algorithms pull request #229
Opened 2022-05-16 14:48 UTC by rosiereflo

closes #228

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of algorithms)
- [x] main documentation was updated (update of input/output file, update of algorithms)
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-05-17 08:03 UTC, adriguir requested changes

2022-05-17 08:03 UTC, adriguir commented on README.md
> +  - **Unitary simulations**: simulations of one or several power systems described in a .jobs file
power systems -> power system test cases

2022-05-17 08:03 UTC, adriguir commented on README.md
> +  - **Systematic analysis**: simulations of a same base power system subject to different events to assess the global stability;
power system test case

2022-05-17 08:03 UTC, adriguir commented on README.md
> +  - **Margin calculation**: simulations of a same base power system with a load variation and subject to different events to compute the maximum load increase in a specific region before the voltage
power system test case

2022-05-17 08:03 UTC, adriguir commented on README.md
> +To build Dyna&omega;o-algorithms you need to clone the repository launch the following commands in the source code directory. it will create a `myEnvDynawoAlgorithms.sh` script file that will be your
clone the repository **and** launch

2022-05-17 08:03 UTC, adriguir commented on README.md
> +To build Dyna&omega;o-algorithms you need to clone the repository launch the following commands in the source code directory. it will create a `myEnvDynawoAlgorithms.sh` script file that will be your
**It** will create

2022-05-17 12:12 UTC, gautierbureau approved these changes

2022-05-19 06:33 UTC, gautierbureau commented
I updated with my commit and rebased with master to resolve conflicts

2022-05-20 12:34 UTC, adriguir approved these changes

2022-05-20 12:34 UTC, merged