#153 In case 100 load increase fail we launch the scenarios for the m…
dynawo/dynawo-algorithms pull request #258
Opened 2022-09-08 14:31 UTC by gautierbureau

…aximum load increase passing.

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of algorithms)
- [ ] main documentation was updated (update of input/output file, update of algorithms)
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-09-15 12:53 UTC, rosiereflo requested changes
Would it be possible to add a nrt ?

2022-09-15 12:53 UTC, rosiereflo commented on sources/Launcher/DYNMarginCalculationLauncher.cpp
> +    findAllLevelsBetween(0., maxVariation, marginCalculation->getAccuracy(), allEvents, toRun);
Why not using minVariation here?

2022-09-15 12:53 UTC, rosiereflo commented on sources/Launcher/DYNMarginCalculationLauncher.cpp
> +  // we force the dichotomie between 0 and 100 event if 100 is not working
typo: even

2022-09-26 08:40 UTC, gautierbureau commented on sources/Launcher/DYNMarginCalculationLauncher.cpp
> +    findAllLevelsBetween(0., maxVariation, marginCalculation->getAccuracy(), allEvents, toRun);
done

2022-09-26 08:41 UTC, gautierbureau commented
> Would it be possible to add a nrt ?

Some nrt already have some issues with 100 and go through the new code, but those nrt have 0 failing and not 100 and 75 passing for example. I don't know if it is simple to create such case...

2022-09-26 09:21 UTC, gautierbureau commented on nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
> +  <loadIncreaseResults loadLevel="0" status="CONVERGENCE">
No as a scenario is not working at 0

2022-09-26 09:22 UTC, gautierbureau commented on nrt/data/IEEE14/MC_failing_load_increase/reference/aggregatedResults.xml
> -  <loadIncreaseResults loadLevel="100" status="CRITERIA_NON_RESPECTED"/>
Not anymore as 0 is not working

2022-09-26 09:25 UTC, rosiereflo commented on nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
> +  <loadIncreaseResults loadLevel="0" status="CONVERGENCE">
well we have to modify the test then as this tests an intermediate result

2022-09-26 09:25 UTC, rosiereflo commented on nrt/data/IEEE14/MC_failing_load_increase/reference/aggregatedResults.xml
> -  <loadIncreaseResults loadLevel="100" status="CRITERIA_NON_RESPECTED"/>
not sure that the platform is going to like it

2022-09-29 13:26 UTC, gautierbureau commented on nrt/data/IEEE14/MC_failing_load_increase/reference/aggregatedResults.xml
> -  <loadIncreaseResults loadLevel="100" status="CRITERIA_NON_RESPECTED"/>
I tested it and it works

2022-09-29 13:48 UTC, gautierbureau commented on nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
> +  <loadIncreaseResults loadLevel="0" status="CONVERGENCE">
only thing I can do is add a new test case witj only the disconnect group event that would yield a margin of 15

2022-10-03 12:23 UTC, rosiereflo commented on nrt/data/IEEE14/MC_file_div/reference/aggregatedResults.xml
> +  <loadIncreaseResults loadLevel="0" status="CONVERGENCE">
why not

2022-10-07 07:47 UTC, rosiereflo approved these changes

2022-10-10 08:27 UTC, rosiereflo commented
I wait before merging this one as I would like the on-going regression on the nrts to be analyzed before redefining the references

2022-10-10 11:58 UTC, gautierbureau commented
> I wait before merging this one as I would like the on-going regression on the nrts to be analyzed before redefining the references

You mean regressions from another dev not this PR ?

2022-10-10 12:00 UTC, rosiereflo commented
> > I wait before merging this one as I would like the on-going regression on the nrts to be analyzed before redefining the references
> 
> You mean regressions from another dev not this PR ?

correct

2022-10-10 12:55 UTC, rosiereflo commented
converting to draft to avoid a merge before nrt are ok

2022-11-21 07:53 UTC, rosiereflo commented
Could you please solve the conflict? The issue on dyn-algo was solved so this one can be merged

2022-11-29 15:09 UTC, merged