188 aggregate results should prioritise convergence status over criteria
dynawo/dynawo-algorithms pull request #293
Opened 2022-12-15 15:47 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of algorithms)
- [ ] main documentation was updated (update of input/output file, update of algorithms)
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-12-15 15:54 UTC, barondim commented
To be merged after https://github.com/dynawo/dynawo/pull/2688

2022-12-15 18:51 UTC, barondim commented
- [ ] create nrt for LOCAL_VALUE and SUM criteria type

2023-01-13 12:40 UTC, rosiereflo commented on nrt/data/IEEE14/SA_convergence_failing_criteria_sum/result/aggregatedResults.xml
> +<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
Is this file useful on github?

2023-01-13 12:51 UTC, barondim commented
- [ ] Please, don't merge. NRTs fail.

2023-01-13 14:15 UTC, rosiereflo requested changes

2023-01-24 15:59 UTC, rosiereflo approved these changes

2023-01-24 16:00 UTC, merged