#378 [Windows] Have a mode with no MPI link for distribution
dynawo/dynawo-algorithms pull request #390
Opened 2024-03-27 16:31 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of algorithms)
- [ ] main documentation was updated (update of input/output file, update of algorithms)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-03-28 10:37 UTC, rosiereflo approved these changes

2024-03-28 10:42 UTC, rosiereflo commented
@gautierbureau Could you please review this one as well? thanks

2024-04-03 09:40 UTC, gautierbureau requested changes
There is too much use of the macro MPI for me. Some `mpi::context().nbProcs() == 1` are not replaced with your new class Process. I think a better design would have been to encapsulate the MPI context all together in a Context class and have all MPI macros use there

2024-04-03 09:40 UTC, gautierbureau commented on sources/Launcher/DYNMarginCalculationLauncher.h
> +  void findOrLaunchLoadIncrease(const boost::shared_ptr<LoadIncrease>& loadIncrease,
I don't get this change

2024-04-03 13:12 UTC, rosiereflo commented
In addition to Gautier's feedback, please make sure to test this in a environment where MPI is not available

2024-04-10 17:04 UTC, barondim commented on sources/Launcher/DYNMarginCalculationLauncher.h
> +  void findOrLaunchLoadIncrease(const boost::shared_ptr<LoadIncrease>& loadIncrease,
I changed the implementation

2024-04-29 15:00 UTC, gautierbureau requested changes

2024-04-29 15:00 UTC, gautierbureau commented on sources/Launcher/DYNMarginCalculationLauncher.cpp
> +#ifdef _MPI_
I would use static_cast<void>(minVariation) etc  and ifndef MPI to handle this case instead of having it in the method definition

2024-04-29 15:07 UTC, gautierbureau commented
`release.yml` and `nightly-release.yml` will need to be updated to produce a no mpi version. This can be bone in another PR. In the meantime it is very easy to test the no mpi version by just editing the `ci.yml` and comment out the mpi steps...

2024-04-29 16:03 UTC, barondim commented
- [ ] To be merged with https://github.com/dynawo/dynaflow-launcher/pull/748

2024-04-30 14:34 UTC, gautierbureau commented
You can squash your commits

2024-05-13 08:08 UTC, gautierbureau approved these changes

2024-05-13 08:08 UTC, merged