307 add method to clean nrt
dynawo/dynawo-algorithms pull request #407
Opened 2024-06-25 13:16 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (update of algorithms)
- [ ] main documentation was updated (update of input/output file, update of algorithms)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-07-01 07:25 UTC, rosiereflo requested changes
the files folder needs to be kept so that the nrt testing the zip inputs work

2024-07-01 08:47 UTC, barondim commented
"the files folder needs to be kept so that the nrt testing the zip inputs work" -> we still test the zip inputs in this new implementation

Moreover we shouldn't modify cpp files in this context -> to make sure we only clean NRT generated files, I decided to generate every output files in a 'outputs' folder. The cpp code was modified to implement this new logic.

2024-07-01 08:59 UTC, rosiereflo commented
> **the files folder needs to be kept so that the nrt testing the zip inputs work ->** we still test the zip inputs in this new implementation
I don't see how it works as the flow first generates the zip from the files folder and then launch the nrts, and there is no modification in the nrt python?

> **Moreover we shouldn't modify cpp files in this context ->** to make sure we only clean NRT generated files, I decided to generate every output files in a 'outputs' folder. The cpp code was modified to implement this new logic.

This will break the integration into the plateform, it isn't possible to do this

2024-07-01 09:15 UTC, rosiereflo commented
> > the files folder needs to be kept so that the nrt testing the zip inputs work -> we still test the zip inputs in this new implementation
> > I don't see how it works as the flow first generates the zip from the files folder and then launch the nrts, and there is no modification in the nrt python?
> 
> The 1st step is to create a 'outputs' folder in the nrt folder and then to zip the archive inside this 'outputs' folder.

As mentioned earlier this outputs folder is not handled by the plateform. Please do not modify how dyn-algo works in this PR

2024-07-02 09:56 UTC, rosiereflo requested changes

2024-07-02 09:56 UTC, rosiereflo commented on util/nrtClean.py
> +    nrt_dir = os.path.join(os.getenv("DYNAWO_ALGORITHMS_NRT_DIR"), "data", "IEEE14")
Another folder than "IEEE14" could be created, we need to iterate inside all the folders in "data"

2024-07-02 09:56 UTC, rosiereflo commented on util/nrtClean.py
> +                if nrt_subfolder == "files":
It would be more genetic to use the cases.py files to find the nrt, as it we create another level of folders this will not work

2024-07-03 06:52 UTC, rosiereflo approved these changes

2024-07-03 06:52 UTC, merged