#48 Minimize reading of IIDM files
dynawo/dynawo-algorithms pull request #49
Opened 2021-06-15 12:15 UTC by lecourtoisflo

When a IIDM file is read multiple times, read it only once, especially during
the multithreading run

requires https://github.com/dynawo/dynawo/pull/1736

2021-06-17 14:01 UTC, rosiereflo requested changes

2021-06-21 06:01 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.cpp
> +    return;
Yes, we will throw. This is the case when no IIDM file is given nor in the init function neither in the job file

2021-06-21 06:07 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.cpp
> +  boost::shared_ptr<DYN::DataInterface> dataInterface = dataInterfaceContainer_->getDataInterface();
OK

2021-06-21 06:10 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.cpp
> + * @file  DYNAnalysisContext.cpp
In that case, I propose more MultiVariantContext, as this is the class used to set the variant in multi threading. What do you think ?

2021-06-21 06:14 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +  const boost::shared_ptr<DYN::DataInterface> referenceDataInterface;
OK

2021-06-21 06:15 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +class DataInterfaceContainer::DataInterfaceContainerImpl {
We don't have access to the thread management in cpp98 so the map cannot exist

2021-06-21 06:16 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +    // compliance
OK

2021-06-21 06:16 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +  boost::shared_ptr<DYN::DataInterface> dataInterface;
OK

2021-06-21 06:17 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +class DataInterfaceContainer::DataInterfaceContainerImpl {
where ?

2021-06-21 06:18 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +DataInterfaceContainer::getDataInterface() const {
it is not "current" as every thread has a different data interface

2021-06-21 06:24 UTC, rosiereflo commented on sources/Launcher/DYNAnalysisContext.cpp
> +    return;
then please add a throw here

2021-06-21 06:25 UTC, rosiereflo commented on sources/Launcher/DYNAnalysisContext.cpp
> + * @file  DYNAnalysisContext.cpp
Context is not clear enough IMHO

2021-06-21 06:25 UTC, rosiereflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +class DataInterfaceContainer::DataInterfaceContainerImpl {
ok, but I mean why do we have the class definitions twice instead of protecting only the different locations with a ifdef?

2021-06-21 06:26 UTC, rosiereflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +class DataInterfaceContainer::DataInterfaceContainerImpl {
Well I think a few comments would help

2021-06-21 06:26 UTC, rosiereflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +DataInterfaceContainer::getDataInterface() const {
getLocal?

2021-06-21 06:27 UTC, lecourtoisflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +    std::cerr << e.what() << std::endl;
OK

2021-06-21 06:27 UTC, lecourtoisflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +
OK

2021-06-21 06:28 UTC, lecourtoisflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.h
> +
OK

2021-06-21 06:30 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.cpp
> +AnalysisContext::init(const std::string& workingDirectory, const std::string& jobFile, unsigned int nbVariants, const std::string& iidmFile) {
For me this is a too specific name that will disturb future maintenance and evolution if new data will be integrated

2021-06-21 06:31 UTC, lecourtoisflo commented on sources/Launcher/DYNSystematicAnalysisLauncher.cpp
> +    std::stringstream ss;
artefact from when I removed the condition. Will be removed

2021-06-21 06:33 UTC, lecourtoisflo commented on sources/Launcher/test/TestDataInterfaceContainer.cpp
> +  ASSERT_NE(dataInterface1, dataInterface);
If one is NULL, the assert TRUE before will fail

2021-06-21 06:34 UTC, lecourtoisflo commented on sources/Launcher/test/TestRobustnessAnalysisLauncher.cpp
> +    context_.init(workingDirectory_, "MyJobs.jobs", 1);
It is a member of the base class, already used in the test

2021-06-21 06:36 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +    if (dataInterfaces.count(thread_id) > 0) {
This function is called when setCurrentVariant is called so at the beginning of the simulation in MT

2021-06-21 06:37 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.cpp
> +    return;
I Will

2021-06-21 06:39 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +class DataInterfaceContainer::DataInterfaceContainerImpl {
It is easier to read that way. If not we'll have a section for the members and a section for each function.

2021-06-21 06:39 UTC, rosiereflo commented on sources/Launcher/DYNAnalysisContext.cpp
> +AnalysisContext::init(const std::string& workingDirectory, const std::string& jobFile, unsigned int nbVariants, const std::string& iidmFile) {
then we need something clearer than "init" as this too generic name makes the code of the margin calculation quite difficult to understand

2021-06-21 06:41 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.h
> +   * @returns data interface
OK

2021-06-21 08:28 UTC, lecourtoisflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.h
> +  AnalysisContext context_;  ///< basic analysis context, common to all
OK

2021-06-21 09:15 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.h
> +    return jobEntry_;
OK

2021-06-21 09:16 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.cpp
> + * @brief Analysis context for data interface
OK

2021-06-21 09:27 UTC, lecourtoisflo commented on sources/Launcher/DYNDataInterfaceContainer.cpp
> +class DataInterfaceContainer::DataInterfaceContainerImpl {
Comments added for initDataInterface, function

2021-06-22 07:14 UTC, lecourtoisflo commented on sources/Launcher/DYNAnalysisContext.h
> + * @file  DYNAnalysisContext.h
OK

2021-06-23 11:12 UTC, rosiereflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +    std::cerr << e.what() << std::endl;
I mean the whole set of differences to display errors, not only this line

2021-06-23 13:13 UTC, lecourtoisflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +    std::cerr << e.what() << std::endl;
Some errors were catched why these new catch and not the old ones so it seems relevant to me to keep them here

2021-06-24 06:54 UTC, rosiereflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +    std::cerr << e.what() << std::endl;
I agree with adding those new catch, but in another PR as it is independent

2021-06-24 06:55 UTC, rosiereflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +    std::cerr << e.what() << std::endl;
(I prefer to keep side developments out of unrelated critical/big PR)

2021-06-24 07:17 UTC, lecourtoisflo commented on sources/Launcher/DYNRobustnessAnalysisLauncher.cpp
> +    std::cerr << e.what() << std::endl;
OK

2021-07-07 08:15 UTC, rosiereflo approved these changes

2021-07-07 08:16 UTC, merged